In [7]:
import numpy as np

In [8]:
lista = [1,2,3,4,5]

In [9]:
lista.__class__

list

In [10]:
a = np.array(lista)

In [11]:
a.dtype

dtype('int64')

In [12]:
a.__class__

numpy.ndarray

In [13]:
a.shape

(5,)

In [14]:
a.ndim

1

In [15]:
b = np.array([[2,2],[4,4]])

In [16]:
print(b)

[[2 2]
 [4 4]]


In [17]:
b.shape

(2, 2)

In [18]:
b.ndim

2

In [19]:
c = np.array([1,2,4,8], ndmin = 3)

In [20]:
print(c)

[[[1 2 4 8]]]


In [21]:
c.shape

(1, 1, 4)

In [22]:
c.ndim

3

In [23]:
d = np.array([1,2,3], dtype=complex)

In [24]:
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [25]:
d.shape

(3,)

In [26]:
x = np.empty([2,3], dtype=int)

In [27]:
x

array([[94331031316370,              0,              0],
       [             0,              0,              0]])

In [28]:
y = np.zeros(3)

In [29]:
y 

array([0., 0., 0.])

In [30]:
z = np.ones(3)
z

array([1., 1., 1.])

In [31]:
# numpy.arange(start, stop,step, dtype)

In [32]:
x = np.arange(2,15,2,dtype=int)
x

array([ 2,  4,  6,  8, 10, 12, 14])

x = np.empty()

the python that is needed for machine learning is:
1. basic syntax
2. classes and functions oops
3. some datastructure which lists,arrays, dictonaries
4. numpy, pandas, seaborn , matplotlib

trigno functions
mathematical functions
reshape and flatten function
save function
transpose function

In [33]:
import random as rd

In [34]:
lista = [rd.randint(0, 100) for _ in range(5)]

In [35]:
lista

[60, 70, 46, 24, 75]

In [36]:
listb = [rd.randint(0, 100) for _ in range(5)]

In [37]:
a = np.array(lista)
b = np.array(listb)

In [42]:
a

array([60, 70, 46, 24, 75])

In [41]:
b

array([93,  3,  2, 36, 65])

In [38]:
c = np.add(a,b)

In [43]:
c

array([153,  73,  48,  60, 140])

In [46]:
c = np.subtract(b,a)
c

array([ 33, -67, -44,  12, -10])

In [48]:
c = np.divide(a,b)
c

array([ 0.64516129, 23.33333333, 23.        ,  0.66666667,  1.15384615])

In [50]:
c = np.multiply(a,b)
c


array([5580,  210,   92,  864, 4875])

In [51]:
d = [4,16,9,25]

In [52]:
d = np.array(d)

In [55]:
c = np.sqrt(d)
c

array([2., 4., 3., 5.])

n/N *(100)

In [56]:
c =np.mean(d)
c

13.5

In [58]:
c =np.percentile(d,25)
c

7.75

a = [1,2,3,4]

In [60]:
c = np.exp(a)
c

array([1.14200739e+26, 2.51543867e+30, 9.49611942e+19, 2.64891221e+10,
       3.73324200e+32])

In [61]:
c = np.log(a)
c

array([4.09434456, 4.24849524, 3.8286414 , 3.17805383, 4.31748811])

In [67]:
c = np.sin(a)
c

array([-0.30481062,  0.77389068,  0.90178835, -0.90557836, -0.38778164])

In [66]:
c  = np.cos(a)
c

array([-0.95241298,  0.6333192 , -0.43217794,  0.42417901,  0.92175127])

In [68]:
c = np.tan(a)
c

array([ 0.32004039,  1.22195992, -2.08661353, -2.1348967 , -0.42070095])

mathematical functions
trigno functions
reshape and flatten functions---> are of utmost importance 

In [70]:
lista = [rd.randint(0, 100) for _ in range(10)]

In [81]:
a = np.array(lista )

In [72]:
a


array([77, 20, 83, 76, 48, 12, 39,  4,  3, 78])

In [82]:
a = a.reshape(5,2)
a


array([[77, 20],
       [83, 76],
       [48, 12],
       [39,  4],
       [ 3, 78]])

In [84]:
a = a.flatten()
a

array([77, 20, 83, 76, 48, 12, 39,  4,  3, 78])

In [88]:
a=[1,2,3,4,5,6,7,8]

a =np.reshape(a,[4,2])

In [89]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [91]:
x=np.transpose(a)

x

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# Sorter way

In [97]:
a = np.arange(8).reshape(4,2).transpose()

In [93]:
a

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])