In [2]:
import numpy as np

In [3]:
lista = [1,2,3,4,5]

In [9]:
lista.__class__

list

In [6]:
a = np.array(lista)

In [7]:
a.dtype

dtype('int64')

In [10]:
a.__class__

numpy.ndarray

In [11]:
a.shape

(5,)

In [12]:
a.ndim

1

In [14]:
b = np.array([[2,2],[4,4]])

In [15]:
print(b)

[[2 2]
 [4 4]]


In [16]:
b.shape

(2, 2)

In [17]:
b.ndim

2

In [18]:
c = np.array([1,2,4,8], ndmin = 3)

In [19]:
print(c)

[[[1 2 4 8]]]


In [20]:
c.shape

(1, 1, 4)

In [21]:
c.ndim

3

In [22]:
d = np.array([1,2,3], dtype=complex)

In [23]:
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [24]:
d.shape

(3,)

In [27]:
x = np.empty([2,3], dtype=int)

In [28]:
x

array([[ 93910559824448,               0,    197568495713],
       [140184799792560, 140185436275696, 140184799792880]])

In [29]:
y = np.zeros(3)

In [30]:
y 

array([0., 0., 0.])

In [32]:
z = np.ones(3)
z

array([1., 1., 1.])

In [ ]:
# numpy.arange(start, stop,step, dtype)

In [34]:
x = np.arange(2,15,2,dtype=int)
x

array([ 2,  4,  6,  8, 10, 12, 14])

x = np.empty()

the python that is needed for machine learning is:
1. basic syntax
2. classes and functions oops
3. some datastructure which lists,arrays, dictonaries
4. numpy, pandas, seaborn , matplotlib

trigno functions
mathematical functions
reshape and flatten function
save function
transpose function

In [2]:
import random as rd

In [3]:
lista = [rd.randint(0, 100) for _ in range(5)]